server:
  port: 9060
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3336/six?characterEncoding=UTF-8&useSSL=true&serverTimezone=PRC&autoReconnect=true
    username: sckr
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: ehcache
  ehcache:
    config: classpath:ehcache.xml
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:com/example/sixshiro/**/*Mapper.xml
  type-aliases-package: com.example.sixshiro
jwt.token.expireTime: 86400000 # 24小时，单位毫秒
